### ISSUE TITLE
Possiblity of Including LivingEntities and Block Collisions 

### ISSUE THREAD

**Issue by LOOHP** [LeGhast/Miniaturise#5]
Perhaps support for LivingEntities and block collisions can be added. I know this might be a stretch, but living entities can be scaled with attributes that might work. As for block collisions, perhaps it could be done with the use of scaled shulkers. 

Lag would also be a concern, so maybe these should be optional per selection.

Just some random thoughts after trying out the plugin. Cool plugin to take advantage of new game features nevertheless!

**Comment by GhastCraftHD** [comment]
Collisions is something that I've thought about adding, but I decided not to. This plugin is just a tool for Block Displays, and one of their features is, that they have no collision. Also I think, that small miniatures would mess up collisions, and it collisions are not applicable for all use cases. Barriers are still a viable option to add faithful collisions though. For LivingEntities I would rather make a seperate plugin. Thanks for sharing your thoughts!
